### ISSUE TITLE
We should not use npx

### ISSUE THREAD

**Issue by ernscht** [namics/env-linter#1]
I would recommend not using this cli with npx.

This for various reasons:
a) The running context for npx is not always the project directory. When e.g. using a node version manager that does not change the complete environment (like nodist) neither the correct node version nor the environment configuration of the project can be found out.
b) Runnability of npx is not given on all environments (on bamboo e.g. you can't use it – )
c) Using npx will first try to load the package from the project if present (--ignore-existing could solve this ;-)
d) And last but not least - Having more controll over usage (API) and better reproducability when loaded as project devDependency – and you'll be more aware when updates are published by maintaining the project.

When I think of npx, it always seems like you never know what you're gonna get.

What do you think?

**Comment by jegli** [comment]
Thank you @ernscht and @smollweide for your inputs and the valuable exchange of ideas!

From our discussions I draw the following conclusions:
- We won't use the env-linter with npx for various reasons (that @ernscht mentioned and other reasons). See below how to use the env-linter in Namics projects. I will update the README accordingly.
- fix: if the used npm version is newer than the npm version that comes with a specific node-version, we won't stop process execution. For this fix I will open a new issue.
- feature request: as part of the versions-check, check the security-flag from [node-list](https://nodejs.org/dist/index.json). I will open a new feature-request for this.
- feature request: as part of the versions-check, check the LTS-flag from [node-list](https://nodejs.org/dist/index.json) (stop process execution if LTS === false). I will open a new feature-request for this.

The recommended way of using env-linter in projects will look like this:
```
{
  "postinstall": "env-linter --hooks-installed --versions --save-exact",
  "prestart": "env-linter --versions",
  "lint-staged": {
    "**/package.json": ["env-linter --save-exact"]
  } 
}
```
